<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Station.Platform.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SqlSugarCore" Version="5.1.4.216" />
    <ProjectReference Include="..\..\Station.Shared\Station.Contracts\Station.Contracts.csproj" />
  </ItemGroup>

</Project>
