<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Station.Spike.Backup</RootNamespace>
    <AssemblyName>Station.Spike.Backup</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Station.Shared\Station.Infrastructure\Station.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.216" />
  </ItemGroup>

</Project>
