<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Station.Spike.StandaloneWebImport</RootNamespace>
    <AssemblyName>Station.Spike.StandaloneWebImport</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Station.Desktop\Station.Desktop.Bootstrapper\Station.Desktop.Bootstrapper.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.216" />
  </ItemGroup>

</Project>
