<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Station.Spike.Kingbase</RootNamespace>
    <AssemblyName>Station.Spike.Kingbase</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kdbndp" Version="8.0.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.216" />
  </ItemGroup>

</Project>
