<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Station.Spike.RealtimePush</RootNamespace>
    <AssemblyName>Station.Spike.RealtimePush</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Station.Shared\Station.Infrastructure\Station.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Station.Platform\Station.Platform.Domain\Station.Platform.Domain.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.11" />
  </ItemGroup>

</Project>
